Repository memgraph/gqlalchemy, pull requests merged in 2022-04, with the labels that each got.

#118 [main < T0049-GA] Remove the argument optional from the Merge class
  gqlalchemy/query_builder.py
  pyproject.toml
Labels: type: bug, status: ready

#111 [develop < T0039-GA] Change where procedure in query builder
  gqlalchemy/exceptions.py
  gqlalchemy/query_builder.py
  tests/docs/test_ogm.py
  tests/docs/test_query_builder.py
  tests/memgraph/test_query_builder.py
Labels: type: bug, status: ready, type: test

#100 [develop < T0035 - GA] Add table to graph importer
  gqlalchemy/loaders.py
  gqlalchemy/memgraph.py
  gqlalchemy/query_builder.py
  poetry.lock
  pyproject.toml
Labels: type: enhancement, status: ready

#114 [develop < T0046-GA] Add order by descending
  gqlalchemy/exceptions.py
  gqlalchemy/query_builder.py
  tests/memgraph/test_query_builder.py
Labels: type: enhancement, status: ready, type: test

#91 [develop < T0001-GA] Memgraph instance runner
  .github/workflows/build-and-test.yml
  docs/reference/gqlalchemy/instance_runner.md
  docs/reference/gqlalchemy/memgraph.md
  docs/reference/gqlalchemy/query_builder.md
  docs/reference/gqlalchemy/utilities.md
  docs/reference/sidebar.json
  gqlalchemy/__init__.py
  gqlalchemy/instance_runner.py
  poetry.lock
  pyproject.toml
  tests/test_instance_runner.py
Labels: type: enhancement, status: ready

#127 [develop < T0043-GA] Update PR template
  .github/pull_request_template.md
Labels: status: ready

#116 [develop < T0048-GA] Update and extend code documentation
  docs/reference/gqlalchemy/connection.md
  docs/reference/gqlalchemy/disk_storage.md
  docs/reference/gqlalchemy/memgraph.md
  docs/reference/gqlalchemy/models.md
  docs/reference/gqlalchemy/query_builder.md
  docs/reference/gqlalchemy/transformations.md
  docs/reference/sidebar.json
  gqlalchemy/disk_storage.py
  gqlalchemy/models.py
  gqlalchemy/query_builder.py
  gqlalchemy/transformations.py
  pydoc-markdown.yml
Labels: status: ready, type: docs
