Repository memgraph/gqlalchemy, pull requests merged in 2022-03, with the labels that each got.

#92 [develop < T0005-GA] Add execute option to query builder
  gqlalchemy/query_builder.py
  tests/docs/test_query_builder.py
  tests/memgraph/test_query_builder.py
Labels: status: ready

#96 [develop < T0013-GA] Create trigger without ON
  gqlalchemy/memgraph.py
  gqlalchemy/models.py
  tests/integration/test_trigger.py
Labels: status: ready

#99 "property" to "item" rename in "where" method and remove spaces when it is a label
  gqlalchemy/query_builder.py
Labels: status: ready

#98 bootstrap_servers argument usage
  gqlalchemy/models.py
  tests/integration/test_stream.py
Labels: status: ready

#86 Add load node test
  tests/ogm/test_load_node.py
Labels: status: ready, type: test

#106 [develop < T0021-GA] Add batch save methods
  gqlalchemy/memgraph.py
  tests/ogm/test_serialisation.py
Labels: status: ready, status: ship it

#113 [develop < T0040-GA] Add index on label
  gqlalchemy/exceptions.py
  gqlalchemy/models.py
  tests/integration/test_index.py
Labels: type: enhancement, status: ship it, type: test

#108 [develop < T0027-GA] Add tests for using nodes and relationships in the query builder
  tests/memgraph/test_query_builder.py
Labels: status: ready

#105 [develop < T0020-GA] Fix label inheritance
  gqlalchemy/models.py
  tests/ogm/test_class_definition.py
Labels: status: ready
