Repository memgraph/gqlalchemy, pull requests merged in 2022-05, with the labels that each got.

#136 [master < T0068-GA] Update README
  README.md
Labels: status: ready

#120 [develop < TOO53-GA] Investigate Timeout error
  .github/workflows/build-and-test.yml
  poetry.lock
  pyproject.toml
Labels: type: bug, status: ready

#139 [develop < T0070-GA] Add more clauses for base classes
  gqlalchemy/__init__.py
  gqlalchemy/query_builder.py
  tests/memgraph/test_query_builder.py
Labels: status: ready

#141 [develop < T0071-GA-bfs-and-shortest-path] added base class and integrated into edge query
  gqlalchemy/memgraph.py
  gqlalchemy/query_builder.py
Labels: type: enhancement, status: ready

#142 [T0071-GA < BFS] add bfs class and tests
  gqlalchemy/memgraph.py
  tests/memgraph/test_query_builder.py
Labels: type: enhancement, status: ready

#128 [develop < T0059-GA] Add SET method to the query builder
  gqlalchemy/exceptions.py
  gqlalchemy/query_builder.py
  tests/memgraph/test_query_builder.py
Labels: type: enhancement, status: ready

#144 [T0071-GA < DFS] add dfs and tests
  gqlalchemy/memgraph.py
  tests/memgraph/test_query_builder.py
Labels: type: enhancement, status: ready

#143 [T0071-GA < wShortest] added WeightedShortestPath and tests
  gqlalchemy/memgraph.py
  tests/memgraph/test_query_builder.py
Labels: type: enhancement, status: ready

#130 [develop < T0026-GA] Wrap query modules
  gqlalchemy/graph_algorithms/__init__.py
  gqlalchemy/graph_algorithms/query_modules.py
  gqlalchemy/memgraph.py
  tests/graph_algorithms/__init__.py
  tests/graph_algorithms/test_query_modules.py
  tests/integration/test_graph_algorithms.py
  tests/integration/test_memgraph.py
Labels: status: ready

#145 [develop < T0081-GA] Rename Edge to Relationship
  gqlalchemy/loaders.py
  gqlalchemy/query_builder.py
  tests/docs/test_query_builder.py
  tests/memgraph/test_query_builder.py
Labels: status: ready

#147 [develop] Move IntegratedAlgorithm, BFS, DFS and weightedShortest from memgraph.py to ./graph_algorithms/
  gqlalchemy/graph_algorithms/integrated_algorithms.py
  gqlalchemy/memgraph.py
  gqlalchemy/query_builder.py
  tests/memgraph/test_query_builder.py
Labels: status: ready

#122 [develop < T0034-GA] Add Field to models
  gqlalchemy/__init__.py
  gqlalchemy/models.py
Labels: type: enhancement, status: ready

#121 [develop < T0054-GA] Add option to suppress warning GQLAlchemySubclassNotFoundWarning
  .github/CODEOWNERS
  gqlalchemy/connection.py
  gqlalchemy/models.py
  tests/conftest.py
Labels: status: ship it, status: discuss it

#148 [develop < T0074-GA] Remove sudo from instance_runner
  gqlalchemy/instance_runner.py
Labels: status: ready

#159 Add argument `lazy` to `Memgraph`
  gqlalchemy/memgraph.py
  tests/memgraph/test_memgraph.py
Labels: status: ready
