Repository memgraph/gqlalchemy, pull requests merged in 2023-04, with the labels that each got.

#198 Remove extra positional argument for `escape_value`
  gqlalchemy/models.py
  tests/ogm/test_properties.py
Labels: type: bug, status: ship it

#235 Make large dependencies optional
  .github/workflows/build-and-test.yml
  gqlalchemy/exceptions.py
  gqlalchemy/transformations/export/graph_transporter.py
  gqlalchemy/transformations/importing/graph_importer.py
  gqlalchemy/transformations/importing/loaders.py
  gqlalchemy/transformations/translators/dgl_translator.py
  gqlalchemy/transformations/translators/translator.py
  gqlalchemy/utilities.py
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/transformations/export/test_export.py
  tests/transformations/importing/test_import.py
  tests/transformations/loaders/test_loaders.py
  tests/transformations/translators/test_dgl_transformations.py
  tests/transformations/translators/test_nx_transformations.py
  tests/transformations/translators/test_pyg_transformations.py
Labels: type: bug, status: ready

#241 Update reference guide
  .github/CODEOWNERS
  docs/reference/gqlalchemy/connection.md
  docs/reference/gqlalchemy/disk_storage.md
  docs/reference/gqlalchemy/exceptions.md
  docs/reference/gqlalchemy/graph_algorithms/integrated_algorithms.md
  docs/reference/gqlalchemy/graph_algorithms/query_modules.md
  docs/reference/gqlalchemy/instance_runner.md
  docs/reference/gqlalchemy/models.md
  docs/reference/gqlalchemy/query_builders/declarative_base.md
  docs/reference/gqlalchemy/query_builders/memgraph_query_builder.md
  docs/reference/gqlalchemy/transformations/export/graph_transporter.md
  docs/reference/gqlalchemy/transformations/export/transporter.md
  docs/reference/gqlalchemy/transformations/importing/graph_importer.md
  docs/reference/gqlalchemy/transformations/importing/loaders.md
  docs/reference/gqlalchemy/transformations/translators/dgl_translator.md
  docs/reference/gqlalchemy/transformations/translators/nx_translator.md
  docs/reference/gqlalchemy/transformations/translators/pyg_translator.md
  docs/reference/gqlalchemy/transformations/translators/translator.md
  docs/reference/gqlalchemy/utilities.md
  docs/reference/gqlalchemy/vendors/database_client.md
  docs/reference/gqlalchemy/vendors/memgraph.md
  docs/reference/gqlalchemy/vendors/neo4j.md
  docs/reference/sidebar.json
  pydoc-markdown.yml
Labels: status: ship it, type: docs

#233 Update installation prerequisites
  README.md
Labels: status: ship it, type: docs
