Repository memgraph/gqlalchemy, pull requests merged in 2024-07, with the labels that each got.

#311 Add latest signatures
  .github/workflows/build-and-test.yml
  gqlalchemy/graph_algorithms/query_builder.py
  tests/graph_algorithms/test_query_builder.py
  tests/integration/test_constraints.py
Labels: status: ready

#306 Adds properties on edges
  docs/how-to-guides/loaders/import-table-data-to-graph-database.md
  docs/reference/gqlalchemy/transformations/importing/loaders.md
  gqlalchemy/transformations/importing/loaders.py
  tests/transformations/loaders/data/address.csv
  tests/transformations/loaders/data/i2a.csv
  tests/transformations/loaders/data/individual.csv
  tests/transformations/loaders/test_loaders.py
Labels: feature, Docs needed

#305 Update load csv docstring
  gqlalchemy/query_builders/memgraph_query_builder.py
Labels: documentation

#304 Add regex operator
  gqlalchemy/query_builders/declarative_base.py
  tests/query_builders/test_query_builders.py
Labels: feature, Docs needed

#310 Add transactions queries
  gqlalchemy/vendors/memgraph.py
  tests/ogm/test_transactions.py
Labels: type: enhancement, status: change

#309 Add storage mode info
  gqlalchemy/vendors/memgraph.py
  tests/conftest.py
  tests/integration/test_storage_modes.py
  tests/ogm/test_storage_modes.py
Labels: type: enhancement, status: ready

#315 Update docs
  docs/reference/gqlalchemy/connection.md
  docs/reference/gqlalchemy/disk_storage.md
  docs/reference/gqlalchemy/exceptions.md
  docs/reference/gqlalchemy/graph_algorithms/integrated_algorithms.md
  docs/reference/gqlalchemy/graph_algorithms/query_builder.md
  docs/reference/gqlalchemy/graph_algorithms/query_modules.md
  docs/reference/gqlalchemy/instance_runner.md
  docs/reference/gqlalchemy/models.md
  docs/reference/gqlalchemy/query_builders/declarative_base.md
  docs/reference/gqlalchemy/query_builders/memgraph_query_builder.md
  docs/reference/gqlalchemy/transformations/export/graph_transporter.md
  docs/reference/gqlalchemy/transformations/export/transporter.md
  docs/reference/gqlalchemy/transformations/importing/graph_importer.md
  docs/reference/gqlalchemy/transformations/importing/loaders.md
  docs/reference/gqlalchemy/transformations/translators/dgl_translator.md
  docs/reference/gqlalchemy/transformations/translators/nx_translator.md
  docs/reference/gqlalchemy/transformations/translators/pyg_translator.md
  docs/reference/gqlalchemy/transformations/translators/translator.md
  docs/reference/gqlalchemy/utilities.md
  docs/reference/gqlalchemy/vendors/database_client.md
  docs/reference/gqlalchemy/vendors/memgraph.md
  docs/reference/gqlalchemy/vendors/neo4j.md
Labels: status: ready

#317 Update changelog and version
  docs/changelog.md
  pyproject.toml
Labels: status: ready
